### PR TITLE
Add project "caer"

### PR DESCRIPTION
**Pull request by jasmcaus**
**What kind of change does this PR introduce?**

- [x] Add a project
- [ ] Update a project
- [ ] Remove a project
- [x] Add or update a category
- [ ] Change configuration
- [ ] Documentation
- [ ] Other, please describe:

**Description:**

The project `caer` was added. Additionally, a new category `Computer/Machine Vision` was introduced in `projects.yaml`. 

I do have a question: `caer` belongs to multiple categories. Should I add re-add the project multiple times (as per the number of categories), or is there a comma-based approach? 

Thank you!

**Checklist:**

- [x] I have read the [CONTRIBUTING](https://github.com/best-of-lists/best-of/blob/main/CONTRIBUTING.md) guidelines.
- [x] I have not modified the `README.md` file. Projects are only supposed to be added or updated within the `projects.yaml` file since the `README.md` file is automatically generated.

### CODE REVIEW

**Comment by lukasmasuch** [comment]
@jasmcaus Thanks for your contribution! We have another best-of list dedicated to machine learning related libraries here: https://github.com/ml-tooling/best-of-ml-python#image-data . `Caer` would be a great fit in the Image Data (`image`) category.

**Comment by jasmcaus** [comment]
@LukasMasuch that's great! I would suggest, however, adding the Computer Vision here too? I can spin up a PR with these changes

**Comment by lukasmasuch** [comment]
@jasmcaus Yep, we can definitely add a computer vision category here. However, we try to not have duplicated projects between our lists, otherwise, it gets to complicated to manage those lists. So, we decided to add the categories to the `higher-level` lists and link to the more specific lists. For example, this is done in here for machine-learning and web-development.

image

I would suggest adding a section for `computer-vision` (or more generally for `image data`) here, which links to the relevant section in the machine-learning list.

**Comment by jasmcaus** [comment]
Okay, got it. But I'm not quite sure how to do that. The best I've done is add a link to the `best-of-ml-python` repo. Feel free to suggest changes. Are you updating the README automatically via github?

**Comment by lukasmasuch** [comment]
```
I do have a question: caer belongs to multiple categories. Should I add re-add the project multiple times (as per the number of categories), or is there a comma-based approach?
```

Unfortunately, a project can only be added to one category, so you need to choose the section that fits best. We also support labels, which can be used for similar purposes (see [here](https://github.com/best-of-lists/best-of-generator#labels)). 

The main reason why we try to keep the number of rendered projects relatively low is that on Github there is a hidden `512kb` limit for rendering the main Readme. Which limits us to show a maximum of about 900-1k projects.

**Comment by jasmcaus** [comment]
Okay, got it. But I'm not quite sure how to do that. The best I've done is add a link to the best-of-ml-python repo. Feel free to suggest changes. Are you updating the README automatically via Github?

**Comment by lukasmasuch** [comment]
This is fine, thanks! Yes, the README will be re-generated automatically every 7 days by GitHub. So, now we just have to wait (I can also trigger it manually) :)

**Comment by jasmcaus** [comment]
That's great! Thanks @LukasMasuch!

**Pull request merged**
